info:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
management:
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: ACCOUNT-SERVICE
    customer: 
      path: /customer/**
      serviceId: CUSTOMER-SERVICE

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG