server:
  port: 8080
spring:
  application:
    name: student-service
  boot:
    admin:
      client:
        url: http://localhost:9999
  cloud:
    consul:
      discovery:
        register: true
        service-name: student-service
      host: localhost
      port: 8500
  datasource:
    password: rasengan
    url: jdbc:mysql://localhost:3306/logs
    username: root
