server:
  port: 8081
spring:
  application:
    name: school-service
  boot:
    admin:
      client:
        url: http://localhost:9999
  cloud:
    consul:
      discovery:
        register: true
        service-name: school-service
      host: localhost
      port: 8500
  datasource:
    url: jdbc:mysql://localhost:3306/logs
    username: root
    password: rasengan