server:
  port: 8081
spring:
  application:
    name: AMS
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace
#server:
#  port: 8081
#spring:
#  datasource:
#    password: rasengan
#    url: jdbc:mysql://localhost:3306/logs
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        dialect: org.hiberante.dialect.MySQL5Dialect
#    show-sql: true
